name: Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      # - name: Cache Next.js build cache
      #   uses: actions/cache@v4
      #   with:
      #     # Cache Next.js bygg-cache
      #     path: ${{ github.workspace }}/apps/web/.next/cache
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('apps/web/package-lock.json') }}-${{ hashFiles('apps/web/**/*.{js,jsx,ts,tsx}') }}
      #     restore-keys: |
      #       ${{ runner.os }}-nextjs-${{ hashFiles('apps/web/package-lock.json') }}-

      - name: npm install and build
        working-directory: apps/web
        run: |
          npm install
          npm run build --standalone
 
      - name: Copy static files
        run: |
          cp -R ./apps/web/public ./apps/web/.next/standalone/public
          cp -R ./apps/web/.next/static ./apps/web/.next/standalone/.next/static

      - name: List standalone directory structure
        working-directory: ./apps/web/.next/standalone
        run: find . -type f -print
        

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./apps/web/.next/standalone
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "next-frontend"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
          package: .
